// Redirects 301 del WordPress viejo (WooCommerce) al sitio Next.
// Fuente: URLs viejas indexadas + slugs actuales de Sanity. Los productos cuyo slug
// no cambió los cubre la regla genérica /product/:slug → /producto/:slug; aquí solo
// van los que cambiaron de slug, los descontinuados (van a su línea) y las categorías.

type Redirect = { source: string; destination: string; permanent: boolean };

const p = (source: string, destination: string): Redirect => ({ source, destination, permanent: true });

export const legacyRedirects: Redirect[] = [
  // Página de descargas del sitio viejo → landing del catálogo.
  p("/descargas", "/catalogo-prolimp"),

  // Productos con slug distinto o descontinuados.
  p("/product/anticochs-gel-quita-cochambre-en-gel", "/producto/quita-cochambre-en-gel-anticochs"),
  p("/product/cetic-100-acido_peracetico", "/producto/cetic-100-acido-peracetico"),
  p("/product/dp1-citrico-desengrasante-neutro-base-citricos", "/producto/desengrasante-para-cocina-dp1-citrico"),
  p("/product/dp1-concentrado-desengrasante-multifuncional", "/producto/desengrasante-dp1-concentrado"),
  p("/product/hipoclorito-de-sodio-al-13-util-para-sanitizar-superficies-pisos-y-paredes", "/producto/hipoclorito-de-sodio-al-13"),
  p("/product/motorlimp-desengrasante-para-motores", "/producto/desengrasante-para-motor-motorlimp"),
  p("/product/odoprol-eliminador-de-malos-olores", "/producto/eliminador-de-malos-olores-odoprol"),
  p("/product/sarriprol-sarricida-desincrustante", "/producto/sarricida-desincrustante-sarriprol"),
  p("/product/clorolimp", "/producto/clorolimp-blanqueador-desinfectante-y-deodorizante-al-6"),
  p("/product/san-100-sanitizante-a-base-de-sales-cuaternarias", "/producto/desinfectante-virucida-san-100"),
  p("/product/jabonlimp-aroma-chicle", "/producto/jabonlimp-shampoo-para-manos-diferentes-aromas"),
  p("/product/jabonlimp-jabon-liquido-aroma-almendras", "/producto/jabon-para-manos-jabonlimp-aroma-almendras"),
  p("/product/jabonlimp-jabon-liquido-para-manos-aroma-campestreaplique-una-pequena-porcion-de-jabonlimp-en-la-palma-de-su-mano-y-friccione-ambas-manos-hasta-obtener-una-suave-y-abundante-espuma-talle-ambas-mano", "/producto/jabonlimp-jabon-liquido-para-manos-aroma-campestreaplique-una-pequena-porcion-de-jabonlimp-en-la"),
  p("/product/ik-alkaline-9", "/productos/jarceria/atomizadores"),
  p("/product/ik-foam-9", "/productos/jarceria/atomizadores"),
  p("/product/ik-foam-pro-12", "/productos/jarceria/atomizadores"),
  p("/product/ik-multi-12bs", "/productos/jarceria/atomizadores"),
  p("/product/kit-medidor-de-cloro-y-ph-para-alberca", "/productos/quimicos/albercas"),
  p("/product/quitamanchas-de-sangre", "/productos/quimicos/lavanderia"),
  p("/product/baston-de-fibra-de-vidrio-1:inch([^/]{1,12})x-1-50-m-amarillo-1906-fy", "/producto/baston-de-fibra-de-vidrio-1inx-1-50-m-amarillo-1906-fy"),
  p("/product/baston-de-fibra-de-vidrio-1:inch([^/]{1,12})x-1-50-m-azul-1906-fb", "/producto/baston-de-fibra-de-vidrio-1inx-1-50-m-azul-1906-fb"),
  p("/product/baston-de-fibra-de-vidrio-1:inch([^/]{1,12})x-1-50-m-rojo-1906-fr", "/producto/baston-de-fibra-de-vidrio-1inx-1-50-m-rojo-1906-fr"),
  p("/product/baston-de-fibra-de-vidrio-1:inch([^/]{1,12})x-1-50-m-verde-1906-fg", "/producto/baston-de-fibra-de-vidrio-1inx-1-50-m-verde-1906-fg"),
  p("/product/baston-de-lamina-1-20-m-rosca-3-4:inch([^/]{1,12})-amarillo-1901-my", "/producto/baston-de-lamina-1-20-m-rosca-3-4in-amarillo-1901-my"),
  p("/product/baston-de-lamina-1-20-m-rosca-3-4:inch([^/]{1,12})-azul-1901-mb", "/producto/baston-de-lamina-1-20-m-rosca-3-4in-azul-1901-mb"),
  p("/product/baston-de-lamina-1-20-m-rosca-3-4:inch([^/]{1,12})-rojo-1901-mr", "/producto/baston-de-lamina-1-20-m-rosca-3-4in-rojo-1901-mr"),
  p("/product/baston-de-lamina-1-20-m-rosca-3-4:inch([^/]{1,12})-verde-1901-mg", "/producto/baston-de-lamina-1-20-m-rosca-3-4in-verde-1901-mg"),
  p("/product/baston-fibra-de-vidrio-1:inch([^/]{1,12})-x-1-20-m-amarillo-1904-fy", "/producto/baston-fibra-de-vidrio-1in-x-1-20-m-amarillo-1904-fy"),
  p("/product/baston-fibra-de-vidrio-1:inch([^/]{1,12})-x-1-20-m-azul-1904-fb", "/producto/baston-fibra-de-vidrio-1in-x-1-20-m-azul-1904-fb"),
  p("/product/baston-fibra-de-vidrio-1:inch([^/]{1,12})-x-1-20-m-rojo-1904-fr", "/producto/baston-fibra-de-vidrio-1in-x-1-20-m-rojo-1904-fr"),
  p("/product/baston-fibra-de-vidrio-1:inch([^/]{1,12})-x-1-20-m-verde-1904-fg", "/producto/baston-fibra-de-vidrio-1in-x-1-20-m-verde-1904-fg"),
  p("/product/brocha-sanitaria-2:inch([^/]{1,12})-amarillo-5002y", "/producto/brocha-sanitaria-2in-amarillo-5002y"),
  p("/product/brocha-sanitaria-2:inch([^/]{1,12})-azul-5002b", "/producto/brocha-sanitaria-2in-azul-5002b"),
  p("/product/brocha-sanitaria-2:inch([^/]{1,12})-rojo-5002r", "/producto/brocha-sanitaria-2in-rojo-5002r"),
  p("/product/brocha-sanitaria-2:inch([^/]{1,12})-verde-5002g", "/producto/brocha-sanitaria-2in-verde-5002g"),
  p("/product/brocha-sanitaria-3:inch([^/]{1,12})-amarillo-5003y", "/producto/brocha-sanitaria-3in-amarillo-5003y"),
  p("/product/brocha-sanitaria-3:inch([^/]{1,12})-azul-5003b", "/producto/brocha-sanitaria-3in-azul-5003b"),
  // Resto de productos: mismo slug, solo cambia el prefijo.
  p("/product/:slug", "/producto/:slug"),

  // Categorías: la paginación de WooCommerce se descarta primero (segundo salto a la categoría).
  p("/product-category/:path*/page/:n(\\d+)", "/product-category/:path*"),
  p("/product-category/3m", "/marca/3m"),
  p("/product-category/accesorios-para-bano", "/productos/jarceria/accesorios-para-bano"),
  p("/product-category/albercas-2", "/productos/quimicos/albercas"),
  p("/product-category/aluminio-y-plasticos-desechables", "/productos/plasticos-desechables/aluminio-y-plasticos-desechables"),
  p("/product-category/aseo-general-2", "/productos/quimicos/aseo-general"),
  p("/product-category/atomizadores", "/productos/jarceria/atomizadores"),
  p("/product-category/automotriz", "/productos/quimicos/automotriz"),
  p("/product-category/banos-2", "/productos/quimicos/banos"),
  p("/product-category/bastones", "/productos/jarceria/bastones"),
  p("/product-category/bolsas", "/productos/plasticos-desechables/bolsas"),
  p("/product-category/botes-de-basura", "/productos/varios/botes-de-basura"),
  p("/product-category/carrito-de-limpieza", "/productos/varios/carrito-de-limpieza"),
  p("/product-category/castor", "/marca/castor"),
  p("/product-category/cepillos", "/productos/jarceria/cepillos"),
  p("/product-category/cocina-2", "/productos/quimicos/cocina"),
  p("/product-category/control-de-aromas-2", "/productos/quimicos/control-aromas"),
  p("/product-category/covid-19", "/productos/quimicos/higiene"),
  p("/product-category/covid-19/higiene-manos", "/productos/quimicos/higiene"),
  p("/product-category/cubetas", "/productos/jarceria/cubetas"),
  p("/product-category/cubrebocas", "/productos/seguridad/cubrebocas"),
  p("/product-category/desinfeccion-organicos", "/productos/quimicos/higiene"),
  p("/product-category/desinfeccion-superficies", "/productos/quimicos/higiene"),
  p("/product-category/desinfectantes", "/productos/quimicos/higiene"),
  p("/product-category/despachador-de-higienicos", "/productos/dosificadores/despachador-de-higienicos"),
  p("/product-category/despachador-de-toalla", "/productos/dosificadores/despachador-de-toalla"),
  p("/product-category/detergentes", "/productos/detergentes"),
  p("/product-category/detergentes2/jabon-de-lavanderia", "/productos/detergentes/jabon-de-lavanderia"),
  p("/product-category/detergentes2/jabon-de-tocador", "/productos/detergentes/jabon-de-tocador"),
  p("/product-category/discos", "/productos/jarceria/discos"),
  p("/product-category/dosificador-de-aroma", "/productos/dosificadores/dosificador-de-aroma"),
  p("/product-category/dosificadores", "/productos/dosificadores"),
  p("/product-category/dosificadores-covid-19", "/productos/dosificadores"),
  p("/product-category/dosificadores/servilleteros", "/productos/dosificadores/servilleteros"),
  p("/product-category/equipo-proteccion", "/productos/seguridad"),
  p("/product-category/equipos", "/productos/seguridad"),
  p("/product-category/escobas", "/productos/jarceria/escobas"),
  p("/product-category/escobetas-y-escobillones", "/productos/jarceria/escobetas-y-escobillones"),
  p("/product-category/especializados", "/productos/quimicos/especializados"),
  p("/product-category/extensiones", "/productos/jarceria/extensiones"),
  p("/product-category/fibras", "/productos/jarceria/fibras"),
  p("/product-category/franelas-y-microfibras", "/productos/jarceria/franelas-y-microfibras"),
  p("/product-category/gorros-y-cofias", "/productos/seguridad/gorros-y-cofias"),
  p("/product-category/guantes", "/productos/seguridad/guantes"),
  p("/product-category/higiene", "/productos/quimicos/higiene"),
  p("/product-category/higiene-manos", "/productos/quimicos/higiene"),
  p("/product-category/higienicos", "/productos/higienicos"),
  p("/product-category/industrial", "/productos/quimicos/industrial"),
  p("/product-category/jabon-de-lavanderia", "/productos/detergentes/jabon-de-lavanderia"),
  p("/product-category/jabon-de-tocador", "/productos/detergentes/jabon-de-tocador"),
  p("/product-category/jabon-hotelero", "/productos/detergentes/jabon-hotelero"),
  p("/product-category/jaboneras", "/productos/dosificadores/jaboneras"),
  p("/product-category/jaladores", "/productos/jarceria/jaladores"),
  p("/product-category/jarceria/bastones", "/productos/jarceria/bastones"),
  p("/product-category/jarcieria", "/productos/jarceria"),
  p("/product-category/jarcieria/accesorios-para-bano", "/productos/jarceria/accesorios-para-bano"),
  p("/product-category/jarcieria/atomizadores", "/productos/jarceria/atomizadores"),
  p("/product-category/jarcieria/bastones", "/productos/jarceria/bastones"),
  p("/product-category/jarcieria/cepillos", "/productos/jarceria/cepillos"),
  p("/product-category/jarcieria/cubetas", "/productos/jarceria/cubetas"),
  p("/product-category/jarcieria/discos", "/productos/jarceria/discos"),
  p("/product-category/jarcieria/escobas", "/productos/jarceria/escobas"),
  p("/product-category/jarcieria/escobetas-y-escobillones", "/productos/jarceria/escobetas-y-escobillones"),
  p("/product-category/jarcieria/extensiones", "/productos/jarceria/extensiones"),
  p("/product-category/jarcieria/fibras", "/productos/jarceria/fibras"),
  p("/product-category/jarcieria/franelas-y-microfibras", "/productos/jarceria/franelas-y-microfibras"),
  p("/product-category/jarcieria/jaladores", "/productos/jarceria/jaladores"),
  p("/product-category/jarcieria/limpia-vidrios", "/productos/jarceria/limpia-vidrios"),
  p("/product-category/jarcieria/recogedores", "/productos/jarceria/recogedores"),
  p("/product-category/jarcieria/trapeadores-mops", "/productos/jarceria/trapeadores-mops"),
  p("/product-category/kimberly-clark", "/marca/kimberly-clark"),
  p("/product-category/lavanderia-2", "/productos/quimicos/lavanderia"),
  p("/product-category/limpia-vidrios", "/productos/jarceria/limpia-vidrios"),
  p("/product-category/panuelos", "/productos/higienicos/panuelos"),
  p("/product-category/papel", "/productos/higienicos"),
  p("/product-category/papel/servitoallas", "/productos/higienicos/servitoallas"),
  p("/product-category/pisos-2", "/productos/quimicos/pisos"),
  p("/product-category/plasticos-y-desechables", "/productos/plasticos-desechables"),
  p("/product-category/plec", "/productos/quimicos/plec"),
  p("/product-category/prolimp", "/marca/prolimp"),
  p("/product-category/quimicos", "/productos/quimicos"),
  p("/product-category/quimicos/albercas-2", "/productos/quimicos/albercas"),
  p("/product-category/quimicos/control-de-aromas-2", "/productos/quimicos/control-aromas"),
  p("/product-category/quimicos/desinfectantes", "/productos/quimicos/higiene"),
  p("/product-category/quimicos/higiene", "/productos/quimicos/higiene"),
  p("/product-category/quimicos/lavanderia-2", "/productos/quimicos/lavanderia"),
  p("/product-category/quimicos/pisos-2", "/productos/quimicos/pisos"),
  p("/product-category/quimicos/plec", "/productos/quimicos/plec"),
  p("/product-category/recogedores", "/productos/jarceria/recogedores"),
  p("/product-category/rubermaid", "/marca/rubbermaid"),
  p("/product-category/scf", "/marca/scf"),
  p("/product-category/secador-de-manos", "/productos/dosificadores/secador-de-manos"),
  p("/product-category/secamanos", "/productos/dosificadores/secador-de-manos"),
  p("/product-category/seguridad", "/productos/seguridad"),
  p("/product-category/seguridad/guantes", "/productos/seguridad/guantes"),
  p("/product-category/senaletica", "/productos/seguridad"),
  p("/product-category/servilletas", "/productos/higienicos/servilletas"),
  p("/product-category/servilleteros", "/productos/dosificadores/servilleteros"),
  p("/product-category/servitoallas", "/productos/higienicos/servitoallas"),
  p("/product-category/tapetes", "/productos/seguridad/tapetes"),
  p("/product-category/toalla-para-manos", "/productos/higienicos/toalla-para-manos"),
  p("/product-category/trapeadores-mops", "/productos/jarceria/trapeadores-mops"),
  p("/product-category/varios", "/productos/varios"),
  p("/product-category/varios/botes-de-basura", "/productos/varios/botes-de-basura"),
  p("/product-category/wiese", "/marca/wiese"),
  // Jarcería: el WP viejo la escribía "jarcieria"; las sublíneas conservan su slug.
  p("/product-category/jarcieria/:sub", "/productos/jarceria/:sub"),
  p("/product-category/jarceria/:sub", "/productos/jarceria/:sub"),
  // Cualquier otra categoría vieja cae al índice de productos.
  p("/product-category/:path*", "/productos"),
];
