import { defineField, defineType } from "sanity";

export const producto = defineType({
  name: "producto",
  title: "Producto",
  type: "document",
  groups: [
    { name: "basico", title: "Básico", default: true },
    { name: "contenido", title: "Contenido" },
    { name: "media", title: "Imágenes y archivos" },
    { name: "relaciones", title: "Relaciones" },
    { name: "seo", title: "SEO" },
  ],
  fields: [
    defineField({ name: "nombre", type: "string", group: "basico", validation: (r) => r.required() }),
    defineField({
      name: "slug",
      type: "slug",
      group: "basico",
      options: { source: "nombre", maxLength: 96 },
      validation: (r) => r.required(),
    }),
    defineField({
      name: "sku",
      title: "SKU / Código",
      type: "string",
      group: "basico",
    }),
    defineField({
      name: "descripcionCorta",
      title: "Descripción corta (listing)",
      type: "text",
      group: "basico",
      rows: 3,
      validation: (r) => r.max(220),
    }),
    defineField({
      name: "descripcion",
      title: "Descripción completa",
      type: "array",
      group: "contenido",
      of: [{ type: "block" }],
    }),
    defineField({
      name: "aplicaciones",
      title: "Aplicaciones y usos",
      type: "array",
      group: "contenido",
      of: [{ type: "string" }],
      options: { layout: "tags" },
    }),
    defineField({
      name: "beneficios",
      title: "Beneficios clave",
      type: "array",
      group: "contenido",
      of: [{ type: "string" }],
    }),
    defineField({
      name: "presentaciones",
      title: "Presentaciones disponibles",
      type: "array",
      group: "contenido",
      of: [
        {
          type: "object",
          fields: [
            { name: "medida", title: "Medida (ej. 500 ml, 5 L, 20 kg)", type: "string" },
            { name: "codigo", title: "SKU/código", type: "string" },
          ],
          preview: { select: { title: "medida", subtitle: "codigo" } },
        },
      ],
    }),
    defineField({
      name: "imagenPrincipal",
      title: "Imagen principal",
      type: "image",
      group: "media",
      options: { hotspot: true },
      fields: [{ name: "alt", type: "string" }],
    }),
    defineField({
      name: "galeria",
      title: "Galería",
      type: "array",
      group: "media",
      of: [{ type: "image", options: { hotspot: true }, fields: [{ name: "alt", type: "string" }] }],
    }),
    defineField({
      name: "fichaTecnica",
      title: "Ficha técnica (PDF)",
      type: "file",
      group: "media",
      options: { accept: "application/pdf" },
    }),
    defineField({
      name: "hojaSeguridad",
      title: "Hoja de seguridad (PDF)",
      type: "file",
      group: "media",
      options: { accept: "application/pdf" },
    }),
    defineField({
      name: "categoria",
      type: "reference",
      to: [{ type: "categoria" }],
      group: "relaciones",
      validation: (r) => r.required(),
    }),
    defineField({
      name: "marca",
      type: "reference",
      to: [{ type: "marca" }],
      group: "relaciones",
    }),
    defineField({
      name: "linea",
      title: "Línea de químicos (solo aplica si es marca Prolimp)",
      type: "reference",
      to: [{ type: "linea" }],
      group: "relaciones",
    }),
    defineField({
      name: "destacado",
      title: "Destacado (aparece en home)",
      type: "boolean",
      group: "basico",
      initialValue: false,
    }),
    defineField({
      name: "activo",
      title: "Activo",
      type: "boolean",
      group: "basico",
      initialValue: true,
    }),
    defineField({
      name: "linkExterno",
      title: "Link externo de compra",
      type: "url",
      group: "basico",
      description: "URL externa donde se puede comprar el producto (opcional).",
    }),
    defineField({ name: "metaTitle", title: "SEO title", type: "string", group: "seo" }),
    defineField({ name: "metaDescription", title: "SEO description", type: "text", group: "seo", rows: 2 }),
  ],
  preview: {
    select: {
      title: "nombre",
      subtitle: "sku",
      media: "imagenPrincipal",
      cat: "categoria.nombre",
    },
    prepare: ({ title, subtitle, media, cat }) => ({
      title,
      subtitle: [cat, subtitle].filter(Boolean).join(" · "),
      media,
    }),
  },
});
